SONARAZDO-397 Track extension size in pull requests

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -60,6 +60,32 @@ build_task:
     - npm run sonarqube
     - npm run upload
 
+check_size_task:
+  <<: *ONLY_SONARSOURCE_QA
+  eks_container:
+    <<: *CONTAINER_TEMPLATE
+    cpu: 3.4
+    memory: 11G
+  env:
+    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
+    SONAR_HOST_URL: VAULT[development/kv/data/next data.url]
+    GPG_SIGNING_KEY: VAULT[development/kv/data/sign data.key]
+    GPG_SIGNING_PASSPHRASE: VAULT[development/kv/data/sign data.passphrase]
+    folder: node_modules
+    SIZE_LIMIT: 30720
+  install_script:
+    - bash scripts/install.sh
+  script:
+    - source cirrus-env BUILD
+    - npm run build
+    - |
+      du -a dist/*.vsix | awk '{print $1}' | xargs -I % bash -c '
+        if [ % -ge $SIZE_LIMIT ]; then
+          echo "Error: File size exceeds limit of $SIZE_LIMIT bytes."
+          exit 1
+        fi
+      '
+
 promote_task:
   depends_on:
     - build
